### ISSUE TITLE
增加 不支持QQ表情 提示

### ISSUE THREAD

**Issue by KaRuichin** [Hellobaka/EmojiMix#1]
不少群友会将`QQ表情`与`Emoji`搞混，请求增加提示以在用户发送了带有`QQ表情`的请求之后告诉用户不支持`QQ表情`。

**Comment by Hellobaka** [comment]
于1.0.2版本加入QQ表情拦截功能，请于[Releases](https://github.com/Hellobaka/EmojiMix/releases/latest)重新下载

**Comment by KaRuichin** [comment]
好耶，~~喜佬透咱.png~~

**Comment by Hellobaka** [comment]
> 好耶，~喜佬透咱~

![kimomo](https://user-images.githubusercontent.com/50934714/154278223-a3369083-6f21-47a5-b83e-fd36c34dcd69.png)
